# config/packages/twig.yaml

twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    exception_controller: null
    form_themes:
        - 'bootstrap_5_layout.html.twig'
    globals:
        app_name: 'Saufolympix'
        app_version: '1.0.0'

when@test:
    twig:
        strict_variables: true